name: Build and Publish to NPM

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "10.14.0"

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Configure Git
        run: |
          git config --local user.email "${{ secrets.EMAIL }}"
          git config --local user.name "GitHub Action"

      - name: Bump version and create tag
        run: |
          pnpm version ${{ github.event.inputs.version_type }} --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          pnpm changelog
          git add package.json CHANGELOG.md
          git commit -m "chore: bump version to v$NEW_VERSION"
          git tag "v$NEW_VERSION"

      - name: Extract changelog for release
        id: get-changelog
        run: |
          # Extract the latest version section from CHANGELOG.md
          if [ -f "CHANGELOG.md" ]; then
            # Get content between the first two version headers or from start to first version header
            CHANGELOG_CONTENT=$(sed -n '/^## \[/,/^## \[/{/^## \[/{p; b}; /^## \[/!p}' CHANGELOG.md | head -n -1 || sed -n '/^## \[/,$p' CHANGELOG.md)
            # Remove the version header line
            CHANGELOG_CONTENT=$(echo "$CHANGELOG_CONTENT" | tail -n +2)
          else
            CHANGELOG_CONTENT="No changelog available."
          fi

          # Escape newlines and quotes for GitHub Actions
          CHANGELOG_CONTENT=$(echo "$CHANGELOG_CONTENT" | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/"/\\"/g')

          echo "changelog=$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT

      - name: Publish to NPM
        run: pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push changes and tags
        run: |
          git push origin main
          git push origin "v$NEW_VERSION"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.NEW_VERSION }}
          name: Release v${{ env.NEW_VERSION }}
          body: |
            ${{ steps.get-changelog.outputs.changelog }}

            ---

            ### Built with
            - Node.js 24
            - pnpm 10.14.0

            *This release was automatically created by GitHub Actions.*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
